# import pandas as pd
# import re
# import tldextract
# from urllib.parse import urlparse


# phishing_urls = [
# "https://brindesserasaexperian.com.br/wp-login.php?redirect_to1=https%3A...",
# "https://briolopacks.com/mnm1146/swps/GLOBE/3701/?dom=track.pliolaktechs.com&m1=&m2=&m3=&m4=Cum%20Phuong%20Mai&m5=&vr=logo#",
# "https://trezorwalletcd.webflow.io/",
# "https://docs.google.com/presentation/d/e/2PACX-1vTqXQfmyWyGbxLjzXRPZ7k...",
# "https://creneau-mondiai.com/pac/calcul.php",
# "http://old.metiztorg-shop.ru/cancel/plex",
# "https://ee-redirect.webb.app/",
# "https://auth-uphold.webflow.io",
# "https://kucoinloyuugene.webflow.io/",
# "https://help-kucoin-login.webflow.io/",
# "https://kucoinuxlogin.webflow.io/",
# "https://sso--coinbasepros--cdn-auths-cdn.webflow.io/...",
# "https://help--ext--cnoibase--uatth.webflow.io/...",
# "https://meetammeklogin.webflow.io/",
# "https://kiucoinlogixn.webflow.io/",
# "https://auth-ttrezorr-login.webflow.io/",
# "https://help-sso-content-ledggir.webflow.io/",
# "https://auth---s--sso-trezur-web.webflow.io/",
# "https://geminilogyin.webflow.io/",
# "https://exaodaasweb3walletf.webflow.io/",
# "https://m-cx-start-ttrezor.webflow.io/",
# "https://auth--web-crypto--cdn--auth.webflow.io/...",
# "https://p-sso-coinbse-help-m-auth.webflow.io/",
# "https://trezor-sso--login.webflow.io/",
# "https://trezeser-hub-suite-en.webflow.io/",
# "https://metamaskxloging.webflow.io/",
# "https://kuyqkcoinlogin.webflow.io/",
# "https://ledgger-leve-app-safe.webflow.io/",
# "https://doc-ledgerlive---cdn.webflow.io/",
# "https://cuikonlogg.webflow.io/",
# "https://avantagesetincitatifs.webflow.io/",
# "https://aauth-starrt-trrzor-console.webflow.io/...",
# "https://m--started-l-edger-oauth.webflow.io/",
# "https://kuccoinlougin.webflow.io/",
# "https://trezor-io-start-r-startin-gg.webflow.io/...",
# "https://api-coinbase-auth.webflow.io/",
# "https://metasksldllguin.webflow.io/",
# "https://cdn--robinhood-com--cdn-g--auth.webflow.io/...",
# "https://zgeminilogin.webflow.io/",
# "https://kucoindlugenh.webflow.io/",
# "https://home-page----coinbase-usa.webflow.io/",
# "https://metamskchrm-extensin.webflow.io/",
# "https://secure--app--coinbasepro--cdn-s-cdn.webflow.io/...",
# "https://geminiloghon.webflow.io/",
# "https://secure--uphoold-com-cdn-auth.webflow.io/...",
# "https://kwqucoinliuogin.webflow.io/",
# "https://aauth-supprt--crpto--authhs.webflow.io/...",
# "https://coainbasseprologin.webflow.io/",
# "https://portal--apps--coinbasepro--cdn--auth.webflow.io/...",
# "https://en--sso---coinbasepro---auth----cdn.webflow.io/...",
# "https://trazor--login--help--desk.webflow.io/",
# "https://koinkeniloginn.webflow.io/",
# "https://apps-site-kucoin.webflow.io/",
# "https://xpertwebinfotech.com/script/index.html",
# "http://fragranciaweb.pro/",
# "https://ambient-finance.com/",
# "https://70off.outletmicado.com/products/7929528811710?variant=49348307...",
# "https://login-htx.life/",
# "https://fragali.sistema2.com.br/?amp%3Butm_source=gotex&%3Butm_medi...",
# "http://64.23.202.212/oboticario/",
# "https://service-onlline.org/YNG/auth/info.php",
# "https://ofertas-exclusivas-cuponsde-abril.com/542871936...",
# "https://eudoraoficiall.store/",
# "https://playpix-fortune.com/",
# "https://playpix-plataforma.com/",
# "https://playpix-baixar.com/",
# "https://ofertas-exclusivas-cuponsde-abril.com/542871936...",
# "https://service-onlline.org/YNG/auth/info.php",
# "https://free.mymapsexpress.com/index.jhtml?partner=^CQ6^xdm870&amp;s2=1411767791157121346&amp;s1=714041",
# "https://espace-oney.fr.service.misajour.spectralgaming.com/login/95401f0bbc7489a8899e831bf52488c6/",
# "https://bw-webupdate.app/",
# "https://1.jornalnot2.com/",
# "https://mlcr0sof7-off1c017.typeform.com/to/ubjpx5/",
# "https://digitale-rakbank.com/app/loginos.php",
# "https://gamestop-memes.web.app/",
# "https://viadeo.journaldunet.com/",
# "https://lien-de-securite.org/MB/auth/info.php",
# "https://bank-raiffeisen.com/de/receive/bank/raiffeisen/232939398...",
# "https://pancake-projclaim.vercel.app/",
# "https://paxful-club.com/#/",
# "https://disq.us/?url=https%3A%2F%2Fwww.gepard.ru%2Flogin%2Faccount%2F&key=JgDq7zS0rAtd6srC39cdig",
# "https://ruekrew.com/girl/courtney-thompson",
# "https://form-us1-461222.public.500apps.org/forms/2...",
# "https://court-order.winstonhausfeld.com/",
# "https://mvia.app/?gad_source=1&gclid=CjwKCAjw_LOwBhBFEiwAmSEQAYpPj...",
# "https://aseguratuvehiculosura.com/sura/soat/",
# "https://indenizacao-digital.com/login-serasa/",
# "https://innowacje-w-osge.com/",
# "https://supercaffeineoficial.shop/",
# "https://donativos.marymount.edu.mx/wp-content/themes/ocawil/?=...",
# "https://segurosysoatmotoscarros.com/",
# "https://segurosvehiculos.co/?gad_source=1&%3Bgclid=EAIaIQobChMI15aa...",
# "https://f91cdb-2.myshopify.com/pages/inicio",
# "https://bitflyer.life/#/pages/base/index/?shiny...",
# "https://agodahotels.live/index/index/home.html",
# "https://santander.co.u...",
# "https://jeffwealth.com/index/login/login/token/dc737dfb0b882535dff63a0...",
# "https://future-energy-orlen.com/",
# "https://secure.na3.documents.adobe.com/public/esign?tsid=CBFCIBAACBSCTBABDUAAABACAABAAUlT3DK7KDsqpOl-YmB2PhoTTB_8kMY9OBh6PdxlEsnwYCpvfWc9SRzcXhc8c5GkfCnxVNQOLKzqykQqFuWbBF2qNlaLEmJnk3WVDDnnjsyVdPN0x0LdCb5O-Y36-ohFq&;",
# "https://briolopacks.com/mnm1146/swps/GLOBE/3701/?dom=track.pliolaktechs.com&m1=&m2=&m3=&m4=Cum%20Phuong%20Mai&m5=&vr=logo#"
# ]
# non_phishing_urls = [
# "https://soha.vn/bao-moi.html",
# "http://kaggle.com/datasets/kunalraut21/legitimate-and-phishing-website-dataset",
# "https://www.google.com/",
# "https://www.bing.com/",
# "https://www.facebook.com/",
# "https://www.instagram.com/",
# "https://www.twitter.com/",
# "https://www.youtube.com/",
# "https://www.tiktok.com/",
# "https://www.pinterest.com/",
# "https://www.snapchat.com/",
# "https://hocvien.haravan.com/blogs/ban-hang-website/top-trang-web-ban-hang-online-hieu-qua-uy-tin-nhat",
# "https://en.wiktionary.org/wiki/luminol",
# "https://www.amazon.com/gp/help/customer/",
# "https://www.yahoo.com/lifestyle/most-effective-exercises-free-weights-100000278.html",
# "https://www.reddit.com/t/amazing/",
# "https://help.netflix.com/legal/termsofuse",
# "https://www.msn.com/vi-vn/sports/other/arne-slot-v%C3%A0-n%E1%BB%97i-%C4%91au-c%C3%B2n-m%C3%A3i-t%E1%BB%AB-az/ar-AA1B0KLI?ocid=BingHp01&cvid=f7f9527f8c594a268645cbf15564c034&ei=7",
# "https://www.microsoft.com/vi-vn/microsoft-365",
# "https://www.nytimes.com/live/2025/03/16/us/trump-news",
# "https://www.w3schools.com/sql/default.asp",
# "https://www.hackerrank.com/blog/",
# "https://codepen.io/challenges",
# "https://vietcombank.com.vn/vi-VN",
# "https://moh.gov.vn/home",
# "https://techcombank.com.vn/",
# "https://www.duolingo.com/",
# "https://x.com/cz_binance/status/1901248382233919743",
# "https://tranco-list.eu/#download",
# "https://openphish.com/",
# "https://elearning.ntu.edu.vn/course/view.php?id=31031",
# "https://www.thesaurus.com/e/ways-to-say/most-common-letter/",
# "https://kenh14.vn/star.chn",
# "https://developer.mozilla.org/en-US/docs/Web/HTML",
# "https://www.freecodecamp.org/",
# "https://shop.forem.com/",
# "https://www.tutorialspoint.com/python/index.htm",
# "https://www.udemy.com/course/complete-ai-guide/",
# "https://nhandan.vn/thong-qua-du-thao-ket-qua-kiem-tra-mot-so-chuyen-de-doi-voi-ban-thuong-vu-tinh-uy-dak-lak-post865546.html",
# "https://dantri.com.vn/the-gioi/ngoai-truong-my-nga-thao-luan-cac-buoc-tiep-theo-cho-van-de-ukraine-20250316192022397.htm",
# "https://cafef.vn/chung-khoan-viet-nam-vung-vang-truoc-gio-tay-188250316220514892.chn",
# "https://vietnamnet.vn/nu-tai-xe-lai-mercedes-tong-hang-loat-xe-may-dang-dung-den-do-2381268.html",
# "https://genk.vn/gia-xe-may-o-muc-thap-hiem-co-honda-vision-con-30-trieu-dong-sh-winner-x-grand-ban-duoi-muc-de-xuat-toi-da-25-trieu-dong-20250316145055723.chn",
# "https://soha.vn/truong-dai-binh-va-loat-thien-tai-trung-quoc-lien-tiep-qua-doi-cai-chet-bi-an-cua-nhung-nhan-vat-noi-tieng-nganh-cong-nghe-1982503161047582.htm",
# "https://www.bbc.com/news/articles/cevx7lkznm1o",
# "https://www.theguardian.com/international",
# "https://www.forbes.com/sites/alisondurkee/2025/03/16/did-trump-administration-defy-immigration-court-order-what-to-know-as-white-house-suggests-immigrants-deported-under-alien-enemies-act/",
# "https://www.bloomberg.com/asia",
# "https://www.npr.org/sections/goats-and-soda/2025/03/16/g-s1-53476/syria-orphanages-assad",
# "https://www.cnbc.com/2025/03/15/trump-administration-message-to-oil-and-gas-industry-youre-the-customer.html",
# "https://www.wsj.com/finance/currencies/trump-trade-tariffs-us-dollar-value-814cbe37?mod=hp_lead_pos1",
# "https://events.stanford.edu/event/ensemble-oh-songs-of-unity?utm_campaign=widget&utm_medium=widget&utm_source=Stanford+University",
# "https://www.dropbox.com/replay#features",
# "https://www.linode.com/",
# "https://www.nih.gov/news-events/news-releases/omalizumab-treats-multi-food-allergy-better-oral-immunotherapy",
# "https://www.noaa.gov/heritage/multimedia/video/gamechangers",
# "https://www.fda.gov/food/alerts-advisories-safety-information/investigation-avian-influenza-h5n1-virus-dairy-cattle",
# "https://www.fidelity.com/retirement-ira/overview",
# "https://www.aljazeera.com/news/liveblog/2025/3/16/live-us-bombs-yemen-killing-13-after-houthis-pause-attacks-on-israel",
# "https://www.walmart.com/ip/FA-SL-NK-MAXI-DRESS/11860359669?classType=VARIANT&athbdg=L1103",
# "https://www.etsy.com/listing/1767572965",
# "https://www.hbomax.com/geo-availability",
# "https://www.notion.com/personal",
# "https://www.paypal.com/us/digital-wallet/ways-to-pay/credit-services",
# "https://www.coinbase.com/price/bitcoin",
# "https://edition.cnn.com/2025/03/16/politics/trump-administration-deportations-alien-enemies-act/index.html",
# "https://proton.me/mail",
# "https://www.zoho.com/mail/?ireft=nhome&src=fa",
# "https://www.box.com/industries/financial-services",
# "https://soundcloud.com/fuzionukg/levels",
# "https://hoathinh3d.mom/tien-nghich",
# "https://dexscreener.com/solana/6oi9cuupcbzk3ykcnnj47ren7lrsuwcsya48umbkemjs",
# "https://www.typingstudy.com/lesson/1",
# "https://www.flutterflow.io/",
# "https://topdev.vn/blog/ngan-xep-va-hang-doi-trong-c/",
# "https://www.shopify.com/pricing",
# "https://slack.com/solutions/engineering",
# "https://global.jd.com/",
# "https://www.taobao.com/",
# "https://blogtruyenmoi.com/c781998/tddv-tap-117",
# "https://vieon.vn/truyen-hinh-truc-tuyen/htv3/",
# "https://hplus.com.vn/xem-kenh-htv2-hd-2669.html",
# "https://kenh14.vn/musik.chn",
# "https://vietteltelecom.vn/",
# "https://vinamilk.com.vn/vi/nhan-hieu",
# "https://scratch.mit.edu/",
# "https://iq.com/album/sat-thu-nhan-tao-phan-2-mau-vat-con-lai-2022-1frz1a7qjt4?lang=vi_vn",
# "https://zigavn.com/",
# "https://playok.com/vi/cotuong/",
# "https://waka.vn/ebook/dac-nhan-tam-dale-carnegie-bYoKVW.html",
# "https://thetealmango.com/technology/6g-network/",
# "https://thinkgeo.com/blog/dijkstras-routing-algorithm",
# "https://linkedin.com/pulse/ospf-open-short-path-first-routing-protocol-using-dijkstra-kohad",
# "https://tuyencongchuc.vn/thong-bao/bo-noi-vu-tuyen-dung-cong-chuc-nam-2024/",
# "https://kplus.vn/",
# "https://cgv.vn/default/aquaman-2.html",
# "https://taimienphi.vn/download-arduino-21997",
# "https://vi.wikipedia.org/wiki/Chanel",
# "https://gucci.com/",
# "https://moi.com.vn/"
# ]


# data = [(url, 1) for url in phishing_urls] + [(url, 0) for url in non_phishing_urls]


# df = pd.DataFrame(data, columns=["URL", "CLASS_LABEL"])


# def extract_features(url):
#     parsed_url = urlparse(url)
#     extracted = tldextract.extract(url)


#     features = {
#         "id": hash(url),
#         "NumDots": url.count('.'),
#         "SubdomainLevel": url.count('.') - 1,
#         "PathLevel": url.count('/'),
#         "UrlLength": len(url),
#         "NumDash": url.count('-'),
#         "NumDashInHostname": extracted.domain.count('-'),
#         "AtSymbol": 1 if "@" in url else 0,
#         "TildeSymbol": 1 if "~" in url else 0,
#         "NumUnderscore": url.count('_'),
#         "NumPercent": url.count('%'),
#         "NumQueryComponents": len(parsed_url.query.split("&")) if parsed_url.query else 0,
#         "NumAmpersand": url.count('&'),
#         "NumHash": url.count('#'),
#         "NumNumericChars": sum(c.isdigit() for c in url),
#         "NoHttps": 1 if parsed_url.scheme != "https" else 0,
#         "RandomString": 1 if re.search(r'[a-zA-Z]{5,}', extracted.domain) else 0,
#         "IpAddress": 1 if re.match(r"\d+\.\d+\.\d+\.\d+", extracted.domain) else 0,
#         "DomainInSubdomains": 1 if extracted.subdomain and extracted.domain in extracted.subdomain else 0,
#         "DomainInPaths": 1 if extracted.domain in parsed_url.path else 0,
#         "HttpsInHostname": 1 if "https" in extracted.domain else 0,
#         "HostnameLength": len(extracted.domain),
#         "PathLength": len(parsed_url.path),
#         "QueryLength": len(parsed_url.query),
#         "DoubleSlashInPath": 1 if "//" in parsed_url.path else 0,
#         "NumSensitiveWords": sum(1 for word in ["login", "bank", "secure"] if word in url.lower()),
#         "EmbeddedBrandName": 1 if re.search(r'facebook|paypal|google', extracted.domain) else 0,
#         "PctExtHyperlinks": 0,
#         "PctExtResourceUrls": 0,
#         "ExtFavicon": 0,
#         "InsecureForms": 0,
#         "RelativeFormAction": 0,
#         "ExtFormAction": 0,
#         "AbnormalFormAction": 0,
#         "PctNullSelfRedirectHyperlinks": 0,
#         "FrequentDomainNameMismatch": 0,
#         "FakeLinkInStatusBar": 0,
#         "RightClickDisabled": 0,
#         "PopUpWindow": 0,
#         "SubmitInfoToEmail": 0,
#         "IframeOrFrame": 0,
#         "MissingTitle": 0,
#         "ImagesOnlyInForm": 0,
#         "SubdomainLevelRT": 0,
#         "UrlLengthRT": 0,
#         "PctExtResourceUrlsRT": 0,
#         "AbnormalExtFormActionR": 0,
#         "ExtMetaScriptLinkRT": 0,
#         "PctExtNullSelfRedirectHyperlinksRT": 0,
#     }
#     return features

# feature_data = df["URL"].apply(extract_features).apply(pd.Series)


# df = pd.concat([df, feature_data], axis=1).drop(columns=["URL"])


# df.to_csv("phishing_dataset_200.csv", index=False)

